name: "Probando Var de Env"

on:
  workflow_dispatch:
    inputs:
      test_env:
        description: '🧪 Test Env to run on'
        required: true
        default: 'qa'
        type: choice
        options:
        - qa
        - uat
        - prod
      premium:
        description: '🔒 Premium User Tests'
        required: true
        default: false
        type: boolean
env:
  TEST_ENV: uat # manual option
  # directly from secret: 
  QA_USERNAME_FREE: ${{ secrets.QA_USERNAME_FREE }}
  QA_USERNAME_PREM: ${{ secrets.QA_USERNAME_PREM }}
  UAT_USERNAME_FREE: ${{ secrets.UAT_USERNAME_FREE }}
  UAT_USERNAME_PREM: ${{ secrets.UAT_USERNAME_PREM }}
  PROD_USERNAME_FREE: ${{ secrets.PROD_USERNAME_FREE }}
  PROD_USERNAME_PREM: ${{ secrets.PROD_USERNAME_PREM }}
  IS_PREMIUM: ${{ github.event.inputs.premium }}

jobs:
  ExecuteTestEnv:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}

    steps:
    - name: Clonar el Repo
      uses: actions/checkout@v4

    - name: Instalar DevDependencies
      run: npm ci

    - name: Run Cypress Tests
      run: npm run test:ci
